# general configuration
url: http://frvl.me
baseurl: ''

# compass configuration
compass:
  # an avatar or logo (optional)
  logo: "/images/compass.png"
  # author will appear under the avatar (optional)
  author: "Filep-Rudamas Vahid-László"
  # tagline will appear under the title (optional)
  tagline: <a href='http://apaczai.ro'>Student</a>, <a href='http://pexels.frvl.me'>photographer</a>, <a href='https://blog.frvl.me'>blogger</a>, done some cool projects around here.
  # if include_content is true, the contents of the content.html include will be
  # added right above the generated item list, if present
  include_content: true
  # if include_analytics is true, the content of the analytics.html include will
  # be added at the end of the <head> section. You can add your Google Analytics
  # Tracking Code to that file.
  include_analytics: false
  # Twitter @username (as defined by the Twitter Card specs)
  twitter: "frvl_me"

# exclude
exclude: ["CNAME", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]

# Dependencies
markdown: kramdown
highlighter: rouge

# Permalinks
permalink: pretty
